<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="base_length" value="0.71" />

  <xacro:property name="base_width" value="0.48" />
  <xacro:property name="base_height" value="0.002" />
  <xacro:property name="base_mass" value="1" />
  <xacro:property name="wheel_radius" value="0.0625" />
  <xacro:property name="wheel_width" value="0.04" />
  <xacro:property name="wheel_pos_x" value="0.0" />
  <xacro:property name="offset_x" value="0.0" />
  <xacro:property name="wheel_offset_y" value="0.02" />
  <xacro:property name="wheel_pos_y" value="${base_width/2-wheel_width/2-wheel_offset_y}" />

  <xacro:property name="wheel_offset_z" value="0.004" />
  <xacro:property name="wheel_pos_z" value="${-wheel_radius+wheel_offset_z}" />
  <xacro:property name="wheel_mass" value=".1" />
  <xacro:property name="wheel_torque" value="20" />
  <xacro:property name="front_caster_wheel" value="true" />
  <xacro:property name="rear_caster_wheel" value="true" />

  <xacro:property name="laser_offset_x" value="0.277" />
  <xacro:property name="laser_offset_y" value="0.162" />
  <xacro:property name="laser_offset_z" value="0.029" />

  <xacro:property name="laser_pose_nanoscan3_front">
    <origin xyz="${laser_offset_x} ${laser_offset_y} ${laser_offset_z}" rpy="3.1415 0 0.7854"/>
  </xacro:property>

  <xacro:property name="laser_pose_nanoscan3_back">
    <origin xyz="${-laser_offset_x} ${-laser_offset_y} ${laser_offset_z}" rpy="3.1415 0 ${3.1415+0.7854}"/>
  </xacro:property>

  <xacro:property name="laser_pose_front_inverted">
    <origin xyz="${base_length/2+offset_x} 0 0.088" rpy="3.1415 0 0"/>
  </xacro:property>

  <xacro:property name="depth_sensor_pose">
    <origin xyz="${0.2+offset_x} 0.0 0.045" rpy="0 0 0"/>
  </xacro:property>

  <xacro:property name="range1_sensor_pose">
    <origin xyz="${offset_x+base_length/2-0.02/2} 0.0 ${-base_height/2-0.01/2}" rpy="0 0 0"/>
  </xacro:property>
  <xacro:property name="range2_sensor_pose">
    <origin xyz="${-0.055+0.02/2} 0.0 ${-base_height/2-0.01/2}" rpy="0 0 3.1415"/>
  </xacro:property>
</robot>
