<?xml version="1.0"?>
<robot name="linorobot2_2wd" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:arg name="namespace" default=""/>

  <xacro:include filename="$(find linorobot2_description)/urdf/zbotlino2_properties.urdf.xacro" />
  <!-- <xacro:include filename="$(find linorobot2_description)/urdf/mech/base.urdf.xacro" /> -->
  <xacro:include filename="$(find linorobot2_description)/urdf/mech/base.offset.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/mech/wheel.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/mech/caster_wheel.offset.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/sensors/imu.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/sensors/generic_laser.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/sensors/camera.urdf.xacro" />
  <!-- <xacro:include filename="$(find linorobot2_description)/urdf/sensors/depth_sensor.urdf.xacro" /> -->
  <xacro:include filename="$(find linorobot2_description)/urdf/sensors/ultrasonic.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/sensors/generic_ultrasonic.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/controllers/diff_drive.urdf.xacro" />

  <xacro:base
    length="${base_length}"
    width="${base_width}"
    height="${base_height}"
    mass="${base_mass}"
    wheel_radius="${wheel_radius}"
    wheel_pos_z="${wheel_pos_z}"
/>

  <xacro:wheel
    side="left"
    radius="${wheel_radius}"
    width="${wheel_width}"
    pos_x="${wheel_pos_x}"
    pos_y="${wheel_pos_y}"
    pos_z="${wheel_pos_z}"
    mass="${wheel_mass}"
  />

  <xacro:wheel
    side="right"
    radius="${wheel_radius}"
    width="${wheel_width}"
    pos_x="${wheel_pos_x}"
    pos_y="${-wheel_pos_y}"
    pos_z="${wheel_pos_z}"
    mass="${wheel_mass}"
  />

  <xacro:if value="${front_caster_wheel}">
    <xacro:caster_wheel
      side="front"
      mass="0.01"
      base_length="${base_length}"
      wheel_radius="${wheel_radius}"
      wheel_pos_z="${wheel_pos_z}"
    />
  </xacro:if>

  <xacro:if value="${rear_caster_wheel}">
    <xacro:caster_wheel
      side="rear"
      mass="0.01"
      base_length="${base_length}"
      wheel_radius="${wheel_radius}"
      wheel_pos_z="${wheel_pos_z}"
    />
  </xacro:if>

  <xacro:imu/>

  <xacro:laser1>
    <xacro:insert_block name="laser_pose_nanoscan3_front" />
  </xacro:laser1>

  <xacro:laser2>
    <xacro:insert_block name="laser_pose_nanoscan3_back" />
  </xacro:laser2>

  <!-- <xacro:depth_sensor> -->
  <!--   <xacro:insert_block name="depth_sensor_pose" /> -->
  <!-- </xacro:depth_sensor> -->

  <xacro:camera>
    <xacro:insert_block name="camera_rear" />
  </xacro:camera>

  <xacro:range1>
    <xacro:insert_block name="range1_sensor_pose" />
  </xacro:range1>
  <xacro:range2>
    <xacro:insert_block name="range2_sensor_pose" />
  </xacro:range2>

  <xacro:range3>
    <xacro:insert_block name="range3_sensor_pose" />
  </xacro:range3>
  <xacro:range4>
    <xacro:insert_block name="range4_sensor_pose" />
  </xacro:range4>

  <xacro:diff_drive_controller
    wheel_separation="${wheel_pos_y * 2}"
    wheel_radius="${wheel_radius}"
    wheel_torque="${wheel_torque}"
  />
</robot>
